#!/bin/bash
# =============================================================================
# build_release.sh -- NetWatch release zip builder
# =============================================================================
# Run this on the production Pi to produce a self-contained release zip that:
#   (A) the update installer can download, verify, and apply to a running Pi
#   (B) install.sh can use as the file source on a fresh install
#
# Usage:
#   bash build_release.sh [version] [description]
#
#   version      Optional. Defaults to the contents of the VERSION file.
#                Use this to override for a public release version (e.g. 1.0.0)
#                without changing the VERSION file first.
#   description  Optional. Human-readable description embedded in manifest.json.
#                Defaults to "NetWatch vVERSION release." if not provided.
#
# Output:
#   ~/backups/releases/netwatch-VERSION.zip
#   SHA-256 printed to stdout -- paste into releases/latest.json
#
# What is included:
#   All .py, .sh, .html, .css, .js, .json, .md, .txt, .conf, .png, .ico, .svg
#   files from ~/netwatch/, with the following excluded:
#     - dev_docs/           (session history, not for users)
#     - config.py           (contains live credentials)
#     - gunicorn.ctl        (runtime socket)
#     - pkg_update.log      (Pi-specific runtime log)
#     - netwatch.db*        (live database)
#     - venv/               (rebuilt by install.sh)
#     - certs/              (Pi-specific, generated by install.sh)
#     - __pycache__/ *.pyc  (compiled bytecode)
#     - *.bak               (patcher backups)
#     - snapshots/          (patcher snapshots)
#     - logs/ data/         (runtime directories)
#     - backups/            (user backups)
#     - updates/            (downloaded update zips)
#     - themes/             (user-created themes, Pi-specific)
#     - .gnupg/             (GPG keyring, Pi-specific)
#     - .git/               (version control internals)
#     - build_release.sh    (this script -- not part of the app)
# =============================================================================

set -euo pipefail

# -- Paths -------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NETWATCH_DIR="$SCRIPT_DIR"
# Use absolute path — $HOME resolves to /nonexistent when running as netwatch-svc
RELEASES_DIR="/home/mboynton/backups/releases"

# -- Version -----------------------------------------------------------------
if [[ -n "${1:-}" ]]; then
    VERSION="$1"
else
    VERSION_FILE="$NETWATCH_DIR/VERSION"
    if [[ ! -f "$VERSION_FILE" ]]; then
        echo "ERROR: VERSION file not found at $VERSION_FILE" >&2
        echo "       Pass a version explicitly: bash build_release.sh 1.0.0" >&2
        exit 1
    fi
    VERSION="$(cat "$VERSION_FILE" | tr -d '[:space:]')"
fi

if [[ -z "$VERSION" ]]; then
    echo "ERROR: Version is empty." >&2
    exit 1
fi

# -- Description -------------------------------------------------------------
if [[ -n "${2:-}" ]]; then
    DESCRIPTION="$2"
else
    DESCRIPTION="NetWatch v${VERSION} release."
fi

OUTPUT_ZIP="$RELEASES_DIR/netwatch-${VERSION}.zip"
WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

echo ""
echo "= Building NetWatch release zip =============="
echo "  Version : $VERSION"
echo "  Source  : $NETWATCH_DIR"
echo "  Output  : $OUTPUT_ZIP"
echo ""

# -- Create output directory --------------------------------------------------
mkdir -p "$RELEASES_DIR"

# -- Exclusion rules ----------------------------------------------------------
# Directories to skip entirely (basename match)
EXCLUDE_DIRS="dev_docs venv certs __pycache__ snapshots logs data backups updates themes .gnupg .git"

# Exact filenames to exclude
EXCLUDE_FILES="config.py gunicorn.ctl pkg_update.log build_release.sh"

# Filename prefixes to exclude
EXCLUDE_PREFIXES="netwatch.db"

# Extensions to exclude
EXCLUDE_EXTS=".pyc .bak .gpg .gz"

# -- Collect files and build manifest actions --------------------------------
echo "  Scanning files..."

MANIFEST_ACTIONS=""
FILE_COUNT=0

while IFS= read -r -d '' full_path; do
    # Get path relative to NETWATCH_DIR
    rel_path="${full_path#$NETWATCH_DIR/}"

    # Skip excluded directories (check each path component)
    skip=false
    IFS='/' read -ra parts <<< "$rel_path"
    for part in "${parts[@]}"; do
        for excl_dir in $EXCLUDE_DIRS; do
            if [[ "$part" == "$excl_dir" ]]; then
                skip=true
                break 2
            fi
        done
    done
    $skip && continue

    # Get just the filename
    fname="$(basename "$rel_path")"

    # Skip excluded filenames
    for excl_file in $EXCLUDE_FILES; do
        if [[ "$fname" == "$excl_file" ]]; then
            skip=true
            break
        fi
    done
    $skip && continue

    # Skip excluded prefixes
    for prefix in $EXCLUDE_PREFIXES; do
        if [[ "$fname" == "$prefix"* ]]; then
            skip=true
            break
        fi
    done
    $skip && continue

    # Skip excluded extensions
    ext="${fname##*.}"
    if [[ "$fname" == *"."* ]]; then
        ext=".${fname##*.}"
    else
        ext=""
    fi
    for excl_ext in $EXCLUDE_EXTS; do
        if [[ "$ext" == "$excl_ext" ]]; then
            skip=true
            break
        fi
    done
    $skip && continue

    # Determine manifest path (what patcher needs)
    # _resolve_path rules:
    #   templates/ prefix -> templates/
    #   static/ prefix    -> static/
    #   releases/ prefix  -> releases/
    #   .html ext         -> templates/basename
    #   .css/.js ext      -> static/basename
    #   everything else   -> basename (lands in NETWATCH_DIR root)
    # We always use the full relative path with subdirectory so it's unambiguous

    manifest_path="$rel_path"

    # Add to manifest actions
    MANIFEST_ACTIONS="${MANIFEST_ACTIONS}    { \"action\": \"replace\", \"file\": \"${manifest_path}\" },\n"

    # Copy file to work dir preserving relative path
    dest_dir="$WORK_DIR/$(dirname "$rel_path")"
    mkdir -p "$dest_dir"
    cp "$full_path" "$WORK_DIR/$rel_path"

    FILE_COUNT=$((FILE_COUNT + 1))

done < <(find "$NETWATCH_DIR" -type f -print0 | sort -z)

echo "  Found $FILE_COUNT files to include."

# -- Write manifest.json ------------------------------------------------------
echo "  Writing manifest.json..."

# -- Write manifest.json using Python for reliable JSON generation -----------
echo "  Writing manifest.json..."

# Write accumulated actions to a temp file (heredoc can't expand bash arrays reliably)
ACTIONS_TMP="$WORK_DIR/_actions.txt"
printf '%b' "$MANIFEST_ACTIONS" > "$ACTIONS_TMP"

# Write description to a temp file to avoid quoting/escaping issues in argv
DESC_TMP="$WORK_DIR/_description.txt"
printf '%s' "$DESCRIPTION" > "$DESC_TMP"

python3 - "$WORK_DIR" "$VERSION" "$ACTIONS_TMP" "$DESC_TMP" << 'PYEOF'
import json, sys, os

work_dir     = sys.argv[1]
version      = sys.argv[2]
actions_file = sys.argv[3]
desc_file    = sys.argv[4]

with open(desc_file) as f:
    description = f.read().strip() or f"NetWatch v{version} release."

with open(actions_file) as f:
    raw = f.read()

actions = []
for line in raw.strip().splitlines():
    line = line.strip().rstrip(',').strip()
    if line:
        try:
            actions.append(json.loads(line))
        except json.JSONDecodeError as e:
            print(f"WARNING: Could not parse action: {line!r} — {e}", file=sys.stderr)

actions.append({"action": "restart", "services": ["monitor", "web"]})

manifest = {
    "version":     version,
    "description": description,
    "actions":     actions,
}

out_path = os.path.join(work_dir, "manifest.json")
with open(out_path, "w") as f:
    json.dump(manifest, f, indent=2)
    f.write("\n")

# Validate
with open(out_path) as f:
    json.load(f)

print(f"  manifest.json written ({len(actions)} actions, validated).")
PYEOF

if [[ $? -ne 0 ]]; then
    echo "ERROR: Failed to write manifest.json" >&2
    exit 1
fi

rm -f "$ACTIONS_TMP"

echo "  manifest.json written."

# -- Build the zip ------------------------------------------------------------
echo "  Building zip..."
rm -f "$OUTPUT_ZIP"
cd "$WORK_DIR"
zip -r "$OUTPUT_ZIP" . -x "*.DS_Store" > /dev/null
cd "$NETWATCH_DIR"

echo "  Zip built."

# -- Compute SHA-256 ----------------------------------------------------------
SHA256="$(sha256sum "$OUTPUT_ZIP" | awk '{print $1}')"
SIZE_KB=$(( $(stat -c%s "$OUTPUT_ZIP") / 1024 ))

echo ""
echo "= Done ======================================="
echo ""
echo "  Output : $OUTPUT_ZIP"
echo "  Size   : ${SIZE_KB} KB"
echo "  SHA-256: $SHA256"
echo ""
echo "  Next steps:"
echo "  1. Upload $OUTPUT_ZIP to GitHub Releases as netwatch-${VERSION}.zip"
echo "  2. Update releases/latest.json:"
echo "       \"version\": \"${VERSION}\","
echo "       \"package_url\": \"https://github.com/mattybusa/NetWatch/releases/download/v${VERSION}/netwatch-${VERSION}.zip\","
echo "       \"package_sha256\": \"${SHA256}\","
echo "  3. Commit and push releases/latest.json to GitHub:"
echo "       sudo -u netwatch-svc git -C /home/mboynton/netwatch add releases/latest.json"
echo "       sudo -u netwatch-svc git -C /home/mboynton/netwatch commit -m \"v${VERSION}: update release manifest\""
echo "       sudo -u netwatch-svc git -C /home/mboynton/netwatch push github main"
echo ""
