# ══════════════════════════════════════════════════════════════════════════════
# NetWatch — config_schema.py
# Master schema for all configuration keys.
#
# Used by:
#   config_validator.py — detects missing/new keys, writes defaults to config.py
#   configeditor.py     — drives the Config Editor UI (fields, types, sections)
#
# Each entry:
#   key         — the Python variable name in config.py
#   default     — safe default value (written if key is missing from config.py)
#   required    — if True, a missing/default value triggers a warning banner
#   group       — logical category (used by the validator)
#   section     — display heading in the Config Editor UI
#   label       — human-readable field name
#   description — hint text shown in Config Editor
#   sensitive   — if True, value is masked in UI (password field)
#   type        — UI field type: "str" | "int" | "bool" | "password"
#   min         — minimum allowed value (int fields only, optional)
#   max         — maximum allowed value (int fields only, optional)
#   ui_hidden   — if True, key is managed by validator but not shown in Config Editor
#
# When adding a new key: fill in ALL fields. group = logical category,
# section = which heading it appears under in the UI. Both are required.
# Set ui_hidden=True only for keys that should never be user-editable via the UI.
# ══════════════════════════════════════════════════════════════════════════════

CONFIG_SCHEMA = [

    # ── Identity ──────────────────────────────────────────────────────────────
    {
        "key":         "SITE_NAME",
        "default":     "NetWatch",
        "required":    False,
        "group":       "identity",
        "section":     "Identity",
        "label":       "Site Name",
        "description": "Displayed in the dashboard header and alert email subjects.",
        "sensitive":   False,
        "type":        "str",
        "ui_hidden":   False,
    },
    {
        "key":         "OWNER_USERNAME",
        "default":     "admin",
        "required":    False,
        "group":       "identity",
        "section":     "Identity",
        "label":       "Owner Username",
        "description": "The admin account treated as the system owner. Used for alert subscriber seeding. Change this if you rename the admin account.",
        "sensitive":   False,
        "type":        "str",
        "ui_hidden":   False,
    },
    {
        "key":         "SECRET_KEY",
        "default":     "CHANGE_THIS_TO_A_RANDOM_SECRET_KEY",
        "required":    True,
        "group":       "identity",
        "section":     "Identity",
        "label":       "Secret Key",
        "description": "Random string used to sign session cookies. Set once manually — not editable via the UI.",
        "sensitive":   True,
        "type":        "str",
        "ui_hidden":   True,   # Set manually in config.py; never exposed in the editor
    },

    # ── Email / Alerts ────────────────────────────────────────────────────────
    {
        "key":         "ALERTS_ENABLED",
        "default":     False,
        "required":    False,
        "group":       "email",
        "section":     "Email & Alerts",
        "label":       "Enable Email Alerts",
        "description": "Set to True to send email alerts. Requires Gmail credentials below.",
        "sensitive":   False,
        "type":        "bool",
        "ui_hidden":   False,
    },
    {
        "key":         "GMAIL_USER",
        "default":     "your_email@gmail.com",
        "required":    False,
        "group":       "email",
        "section":     "Email & Alerts",
        "label":       "Gmail Address",
        "description": "Your Gmail address. Used to send both alert emails and backup emails.",
        "sensitive":   False,
        "type":        "str",
        "ui_hidden":   False,
    },
    {
        "key":         "GMAIL_APP_PASSWORD",
        "default":     "your_app_password_here",
        "required":    False,
        "group":       "email",
        "section":     "Email & Alerts",
        "label":       "Gmail App Password",
        "description": "Gmail App Password (not your login password). Get one at myaccount.google.com → Security → App Passwords.",
        "sensitive":   True,
        "type":        "password",
        "ui_hidden":   False,
    },
    {
        "key":         "ALERT_TO",
        "default":     "your_email@gmail.com",
        "required":    False,
        "group":       "email",
        "section":     "Email & Alerts",
        "label":       "Send Alerts To",
        "description": "Email address where alerts and backup emails are delivered. Can be any email address.",
        "sensitive":   False,
        "type":        "str",
        "ui_hidden":   False,
    },

    # ── Network Targets ───────────────────────────────────────────────────────
    {
        "key":         "LAN_GATEWAY",
        "default":     "192.168.1.1",
        "required":    True,
        "group":       "network",
        "section":     "Network Targets",
        "label":       "LAN Gateway IP",
        "description": "Your wired router gateway. Pinged to confirm LAN is alive.",
        "sensitive":   False,
        "type":        "str",
        "ui_hidden":   False,
    },
    {
        "key":         "WAN_PRIMARY",
        "default":     "8.8.8.8",
        "required":    True,
        "group":       "network",
        "section":     "Network Targets",
        "label":       "WAN Primary Target",
        "description": "Primary external IP to ping to confirm internet connectivity. Default: 8.8.8.8",
        "sensitive":   False,
        "type":        "str",
        "ui_hidden":   False,
    },
    {
        "key":         "WAN_SECONDARY",
        "default":     "8.8.4.4",
        "required":    False,
        "group":       "network",
        "section":     "Network Targets",
        "label":       "WAN Secondary Target",
        "description": "Secondary external IP, used if primary fails. Default: 8.8.4.4",
        "sensitive":   False,
        "type":        "str",
        "ui_hidden":   False,
    },
    {
        "key":         "DNS_TEST_HOST",
        "default":     "google.com",
        "required":    False,
        "group":       "network",
        "section":     "Network Targets",
        "label":       "DNS Test Hostname",
        "description": "Hostname resolved to test DNS. Default: google.com",
        "sensitive":   False,
        "type":        "str",
        "ui_hidden":   False,
    },
    {
        "key":         "WIFI_GATEWAY",
        "default":     "",
        "required":    False,
        "group":       "network",
        "section":     "Network Targets",
        "label":       "WiFi AP Gateway IP",
        "description": "Gateway IP of your wireless network. Pinged to detect AP failures.",
        "sensitive":   False,
        "type":        "str",
        "ui_hidden":   False,
    },

    # ── Network Interfaces ────────────────────────────────────────────────────
    {
        "key":         "LAN_INTERFACE",
        "default":     "",
        "required":    False,
        "group":       "network",
        "section":     "Network Interfaces",
        "label":       "LAN Interface",
        "description": "Network interface to use for LAN checks (e.g. eth0). "
                       "If set, pings are forced out this interface and the interface "
                       "must have an IP or the check fails. Leave blank for unbound "
                       "(OS chooses interface).",
        "sensitive":   False,
        "type":        "str",
        "ui_hidden":   False,
    },
    {
        "key":         "WIFI_INTERFACE",
        "default":     "",
        "required":    False,
        "group":       "network",
        "section":     "Network Interfaces",
        "label":       "WiFi Interface",
        "description": "Network interface to use for WiFi AP checks (e.g. wlan0). "
                       "If set, pings are forced out this interface and the interface "
                       "must have an IP or the check fails. Leave blank for unbound "
                       "(OS chooses interface).",
        "sensitive":   False,
        "type":        "str",
        "ui_hidden":   False,
    },

    # ── GPIO Pins ─────────────────────────────────────────────────────────────
    {
        "key":         "RELAY_MODEM",
        "default":     17,
        "required":    True,
        "group":       "gpio",
        "section":     "GPIO Pins",
        "label":       "Modem Relay GPIO Pin",
        "description": "BCM pin number connected to Relay 1 (modem power). Default: 17",
        "sensitive":   False,
        "type":        "int",
        "ui_hidden":   False,
    },
    {
        "key":         "RELAY_ROUTER",
        "default":     27,
        "required":    True,
        "group":       "gpio",
        "section":     "GPIO Pins",
        "label":       "Router Relay GPIO Pin",
        "description": "BCM pin number connected to Relay 2 (router power). Default: 27",
        "sensitive":   False,
        "type":        "int",
        "ui_hidden":   False,
    },
    {
        "key":         "BUTTON_PIN",
        "default":     22,
        "required":    False,
        "group":       "gpio",
        "section":     "GPIO Pins",
        "label":       "Button GPIO Pin",
        "description": "BCM pin number connected to the pushbutton. Default: 22",
        "sensitive":   False,
        "type":        "int",
        "ui_hidden":   False,
    },
    {
        "key":         "RELAY_ACTIVE_LOW",
        "default":     False,
        "required":    False,
        "group":       "gpio",
        "section":     "GPIO Pins",
        "label":       "Relays Active LOW",
        "description": "True for most relay boards (relay fires when GPIO is LOW). Flip to False if relays behave backwards.",
        "sensitive":   False,
        "type":        "bool",
        "ui_hidden":   False,
    },

    # ── Timing ────────────────────────────────────────────────────────────────
    {
        "key":         "CHECK_INTERVAL",
        "default":     30,
        "required":    False,
        "group":       "timing",
        "section":     "Timing",
        "label":       "Check Interval (seconds)",
        "description": "How often the monitor checks network health. Default: 30 seconds.",
        "sensitive":   False,
        "type":        "int",
        "min":         10,
        "max":         300,
        "ui_hidden":   False,
    },
    {
        "key":         "CONFIRM_WINDOW",
        "default":     180,
        "required":    False,
        "group":       "timing",
        "section":     "Timing",
        "label":       "Confirmation Window (seconds)",
        "description": "An issue must persist for this long before any reset is triggered. Prevents reacting to brief blips. Default: 180 (3 minutes).",
        "sensitive":   False,
        "type":        "int",
        "min":         30,
        "max":         600,
        "ui_hidden":   False,
    },
    {
        "key":         "RESET_COOLDOWN",
        "default":     1800,
        "required":    False,
        "group":       "timing",
        "section":     "Timing",
        "label":       "Reset Cooldown (seconds)",
        "description": "Minimum time between automatic resets. Prevents reboot loops. Default: 1800 (30 minutes).",
        "sensitive":   False,
        "type":        "int",
        "min":         60,
        "max":         7200,
        "ui_hidden":   False,
    },
    {
        "key":         "MODEM_BOOT_DELAY",
        "default":     60,
        "required":    False,
        "group":       "timing",
        "section":     "Timing",
        "label":       "Modem Boot Delay (seconds)",
        "description": "After modem power is restored, wait this long before powering the router. Allows modem to authenticate with ISP. Default: 60.",
        "sensitive":   False,
        "type":        "int",
        "min":         30,
        "max":         300,
        "ui_hidden":   False,
    },
    {
        "key":         "ROUTER_BOOT_DELAY",
        "default":     30,
        "required":    False,
        "group":       "timing",
        "section":     "Timing",
        "label":       "Router Boot Delay (seconds)",
        "description": "After router power is restored, wait this long before resuming health checks. Default: 30.",
        "sensitive":   False,
        "type":        "int",
        "min":         10,
        "max":         180,
        "ui_hidden":   False,
    },
    {
        "key":         "POWER_CYCLE_OFF_TIME",
        "default":     5,
        "required":    False,
        "group":       "timing",
        "section":     "Timing",
        "label":       "Power Off Duration (seconds)",
        "description": "How long power stays cut during a relay cycle. Default: 5 seconds.",
        "sensitive":   False,
        "type":        "int",
        "min":         2,
        "max":         30,
        "ui_hidden":   False,
    },
    {
        "key":         "MAX_RESETS_PER_DAY",
        "default":     5,
        "required":    False,
        "group":       "timing",
        "section":     "Timing",
        "label":       "Max Auto Resets Per Day",
        "description": "After this many automatic resets in one day, enter conservative mode (no further resets). Default: 5.",
        "sensitive":   False,
        "type":        "int",
        "min":         1,
        "max":         20,
        "ui_hidden":   False,
    },
    {
        "key":         "SPEEDTEST_INTERVAL",
        "default":     7200,
        "required":    False,
        "group":       "timing",
        "section":     "Timing",
        "label":       "Speedtest Interval (seconds)",
        "description": "How often to run a speedtest when the network is healthy. Default: 7200 (2 hours).",
        "sensitive":   False,
        "type":        "int",
        "min":         1800,
        "max":         86400,
        "ui_hidden":   False,
    },

    # ── Alert Thresholds ──────────────────────────────────────────────────────
    {
        "key":         "LATENCY_WARN_MS",
        "default":     150,
        "required":    False,
        "group":       "thresholds",
        "section":     "Alert Thresholds",
        "label":       "Latency Warning Threshold (ms)",
        "description": "Latency above this is considered degraded. Default: 150ms.",
        "sensitive":   False,
        "type":        "int",
        "min":         20,
        "max":         1000,
        "ui_hidden":   False,
    },
    {
        "key":         "PACKET_LOSS_WARN",
        "default":     10,
        "required":    False,
        "group":       "thresholds",
        "section":     "Alert Thresholds",
        "label":       "Packet Loss Warning Threshold (%)",
        "description": "Packet loss above this percentage is considered degraded. Default: 10%.",
        "sensitive":   False,
        "type":        "int",
        "min":         1,
        "max":         50,
        "ui_hidden":   False,
    },
    {
        "key":         "DEGRADED_ALERT_TIME",
        "default":     900,
        "required":    False,
        "group":       "thresholds",
        "section":     "Alert Thresholds",
        "label":       "Degraded Alert Delay (seconds)",
        "description": "How long the network must be degraded before a degradation alert is sent. Default: 900 (15 minutes).",
        "sensitive":   False,
        "type":        "int",
        "min":         60,
        "max":         3600,
        "ui_hidden":   False,
    },

    # ── Data Retention ────────────────────────────────────────────────────────
    {
        "key":         "SNAPSHOT_RETENTION",
        "default":     10,
        "required":    False,
        "group":       "retention",
        "section":     "Data Retention",
        "label":       "Snapshot Retention Count",
        "description": "Number of pre-install snapshots to keep. Older ones are pruned when a new snapshot is taken.",
        "sensitive":   False,
        "type":        "int",
        "min":         1,
        "max":         50,
        "ui_hidden":   False,
    },
    {
        "key":         "KEEP_HEALTH_DAYS",
        "default":     30,
        "required":    False,
        "group":       "retention",
        "section":     "Data Retention",
        "label":       "Health Record Retention (days)",
        "description": "Days of per-check health records to keep. Default: 30.",
        "sensitive":   False,
        "type":        "int",
        "min":         7,
        "max":         365,
        "ui_hidden":   False,
    },
    {
        "key":         "KEEP_RESET_DAYS",
        "default":     90,
        "required":    False,
        "group":       "retention",
        "section":     "Data Retention",
        "label":       "Reset Record Retention (days)",
        "description": "Days of reset event records to keep. Default: 90.",
        "sensitive":   False,
        "type":        "int",
        "min":         7,
        "max":         365,
        "ui_hidden":   False,
    },
    {
        "key":         "KEEP_SPEEDTEST_DAYS",
        "default":     90,
        "required":    False,
        "group":       "retention",
        "section":     "Data Retention",
        "label":       "Speedtest Record Retention (days)",
        "description": "Days of speedtest results to keep. Default: 90.",
        "sensitive":   False,
        "type":        "int",
        "min":         7,
        "max":         365,
        "ui_hidden":   False,
    },
    {
        "key":         "DB_BACKUP_RETENTION",
        "default":     14,
        "required":    False,
        "group":       "retention",
        "section":     "Data Retention",
        "label":       "DB Backup Retention (count)",
        "description": "Number of daily database backup files to keep locally on the Pi. Older ones are pruned automatically. Default: 14 (2 weeks).",
        "sensitive":   False,
        "type":        "int",
        "min":         1,
        "max":         90,
        "ui_hidden":   False,
    },
    {
        "key":         "FULL_BACKUP_RETENTION",
        "default":     7,
        "required":    False,
        "group":       "retention",
        "section":     "Data Retention",
        "label":       "Full Backup Retention (count)",
        "description": "Number of full system backup files to keep locally on the Pi. Older ones are pruned automatically. Default: 7.",
        "sensitive":   False,
        "type":        "int",
        "min":         1,
        "max":         30,
        "ui_hidden":   False,
    },

    {
        "key":         "SUMMARY_FREQUENCY",
        "default":     "daily",
        "required":    False,
        "group":       "alerts",
        "section":     "Alerts",
        "label":       "Summary Frequency",
        "description": "How often to send the network summary email. "
                       "<b>daily</b> = every day at SUMMARY_HOUR. "
                       "<b>weekly</b> = once per week on SUMMARY_DAY at SUMMARY_HOUR.",
        "allowed_values": ["daily", "weekly"],
        "sensitive":   False,
        "type":        "str",
        "ui_hidden":   False,
    },
    {
        "key":         "SUMMARY_DAY",
        "default":     0,
        "required":    False,
        "group":       "alerts",
        "section":     "Alerts",
        "label":       "Summary Day (weekly only)",
        "description": "Day of week to send the summary when SUMMARY_FREQUENCY=weekly. "
                       "<b>0</b>=Monday, <b>1</b>=Tuesday, <b>2</b>=Wednesday, "
                       "<b>3</b>=Thursday, <b>4</b>=Friday, <b>5</b>=Saturday, <b>6</b>=Sunday.",
        "day_names":     ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
        "sensitive":   False,
        "type":        "int",
        "min":         0,
        "max":         6,
        "ui_hidden":   False,
    },
    {
        "key":         "SUMMARY_HOUR",
        "default":     8,
        "required":    False,
        "group":       "alerts",
        "section":     "Alerts",
        "label":       "Summary Send Hour (0-23)",
        "description": "Hour of day (local time, 24h) at which to send the network summary email. "
                       "Default: <b>8</b> (8 AM). Valid range: <b>0</b>–<b>23</b>.",
        "sensitive":   False,
        "type":        "int",
        "min":         0,
        "max":         23,
        "ui_hidden":   False,
    },

    {
        "key":         "SUMMARY_SHOW_UPTIME",
        "default":     True,
        "required":    False,
        "group":       "alerts",
        "section":     "Alerts",
        "label":       "Summary: Show Uptime Stats",
        "description": "Include uptime percentages (1h, 24h, 7d, 30d) in the summary email.",
        "sensitive":   False,
        "type":        "bool",
        "ui_hidden":   False,
    },
    {
        "key":         "SUMMARY_SHOW_RESETS",
        "default":     True,
        "required":    False,
        "group":       "alerts",
        "section":     "Alerts",
        "label":       "Summary: Show Reset Count",
        "description": "Include the number of automatic resets in the summary period.",
        "sensitive":   False,
        "type":        "bool",
        "ui_hidden":   False,
    },
    {
        "key":         "SUMMARY_SHOW_LATENCY",
        "default":     True,
        "required":    False,
        "group":       "alerts",
        "section":     "Alerts",
        "label":       "Summary: Show Current Latency & Packet Loss",
        "description": "Include a snapshot of current latency and packet loss at send time.",
        "sensitive":   False,
        "type":        "bool",
        "ui_hidden":   False,
    },
    {
        "key":         "SUMMARY_SHOW_SPEEDTEST",
        "default":     False,
        "required":    False,
        "group":       "alerts",
        "section":     "Alerts",
        "label":       "Summary: Show Speedtest Results",
        "description": "Include average download/upload speeds and ping from tests run in the summary period.",
        "sensitive":   False,
        "type":        "bool",
        "ui_hidden":   False,
    },
    {
        "key":         "SUMMARY_SHOW_RESET_LOG",
        "default":     False,
        "required":    False,
        "group":       "alerts",
        "section":     "Alerts",
        "label":       "Summary: Show Reset Log",
        "description": "Include a log of each individual reset event (time and type) in the summary period.",
        "sensitive":   False,
        "type":        "bool",
        "ui_hidden":   False,
    },

    # ── Security ──────────────────────────────────────────────────────────────
    {
        "key":         "LOCKOUT_FAIL_THRESHOLD",
        "default":     5,
        "required":    False,
        "group":       "thresholds",
        "section":     "Security",
        "label":       "Login Failures Before Lockout",
        "description": "Failed login attempts within 5 minutes before account is temporarily locked. Default: 5.",
        "sensitive":   False,
        "type":        "int",
        "min":         3,
        "max":         20,
        "ui_hidden":   False,
    },
    {
        "key":         "LOCKOUT_DURATION_MINUTES",
        "default":     30,
        "required":    False,
        "group":       "thresholds",
        "section":     "Security",
        "label":       "Lockout Duration (minutes)",
        "description": "How long a locked account stays locked before auto-unlocking. Default: 30.",
        "sensitive":   False,
        "type":        "int",
        "min":         1,
        "max":         1440,
        "ui_hidden":   False,
    },
    {
        "key":         "LOCKOUT_MAX_COUNT",
        "default":     3,
        "required":    False,
        "group":       "thresholds",
        "section":     "Security",
        "label":       "Lockouts Before Auto-Disable",
        "description": "Lockouts within the window before account is auto-disabled (requires admin to re-enable). Default: 3.",
        "sensitive":   False,
        "type":        "int",
        "min":         1,
        "max":         10,
        "ui_hidden":   False,
    },
    {
        "key":         "LOCKOUT_WINDOW_HOURS",
        "default":     24,
        "required":    False,
        "group":       "thresholds",
        "section":     "Security",
        "label":       "Lockout Count Window (hours)",
        "description": "Time window for counting lockouts toward auto-disable. Default: 24.",
        "sensitive":   False,
        "type":        "int",
        "min":         1,
        "max":         168,
        "ui_hidden":   False,
    },
    {
        "key":         "FORCED_CHANGE_TIMEOUT_MINUTES",
        "default":     10,
        "required":    False,
        "group":       "thresholds",
        "section":     "Security",
        "label":       "Forced Password Change Timeout (minutes)",
        "description": "Time allowed to complete a forced password change before session expires. Default: 10.",
        "sensitive":   False,
        "type":        "int",
        "min":         2,
        "max":         60,
        "ui_hidden":   False,
    },

    {
        "key":         "MFA_ISSUER",
        "default":     "NetWatch",
        "required":    False,
        "group":       "auth",
        "section":     "Security",
        "label":       "MFA Issuer Name",
        "description": "Name shown in authenticator apps (e.g. Google Authenticator) when users set up MFA. Default: NetWatch.",
        "sensitive":   False,
        "type":        "str",
        "ui_hidden":   False,
    },

    {
        "key":         "MFA_REQUIRED",
        "default":     True,
        "required":    False,
        "group":       "auth",
        "section":     "Security",
        "label":       "Require MFA for Admin/Operator",
        "description": "When enabled, Admin and Operator accounts must set up multi-factor "
                       "authentication within the grace period. When disabled, MFA becomes "
                       "optional for all roles — existing MFA setups still work but are not "
                       "enforced. Requires service restart to take effect.",
        "sensitive":   False,
        "type":        "bool",
        "ui_hidden":   False,
    },

    # ── Logging ───────────────────────────────────────────────────────────────
    {
        "key":         "LOG_FORMAT",
        "default":     "pretty",
        "required":    False,
        "group":       "logging",
        "section":     "Logging",
        "label":       "Log Format",
        "description": "pretty = human-readable output for SSH/journalctl. "
                       "json = structured JSON output for Loki/log aggregation. "
                       "Requires service restart to take effect.",
        "sensitive":   False,
        "type":        "str",
        "ui_hidden":   False,
    },

    # ── Server ────────────────────────────────────────────────────────────────
    {
        "key":         "DASHBOARD_HOST",
        "default":     "0.0.0.0",
        "required":    False,
        "group":       "dashboard",
        "section":     "Server",
        "label":       "Dashboard Bind Address",
        "description": "Network interface Flask binds to. 0.0.0.0 = all interfaces (default). Change requires service restart.",
        "sensitive":   False,
        "type":        "str",
        "ui_hidden":   False,
    },
    {
        "key":         "DASHBOARD_PORT",
        "default":     5000,
        "required":    False,
        "group":       "dashboard",
        "section":     "Server",
        "label":       "Dashboard Port",
        "description": "Port NetWatch listens on. Default: 5000. Changing this requires updating bookmarks and firewall rules. Requires service restart.",
        "sensitive":   False,
        "type":        "int",
        "min":         1024,
        "max":         65535,
        "ui_hidden":   False,
    },
    {
        "key":         "UPDATE_CHECK_URL",
        "default":     "https://raw.githubusercontent.com/mattybusa/NetWatch/main/releases/latest.json",
        "required":    False,
        "group":       "system",
        "section":     "System",
        "label":       "Update Check URL",
        "description": "URL of the update manifest JSON. NetWatch polls this daily to check for new versions. Leave blank to disable update checking.",
        "sensitive":   False,
        "type":        "str",
        "ui_hidden":   False,
    },
    {
        "key":         "DEVELOPMENT_SYSTEM",
        "default":     False,
        "required":    False,
        "group":       "system",
        "section":     "System",
        "label":       "Development System",
        "description": "When True, enables the Release Manager in the Admin page for building and publishing releases to GitHub. Never set this on a user install.",
        "sensitive":   False,
        "type":        "bool",
        "ui_hidden":   True,   # Set manually in config.py; never shown in Config Editor
    },
]

# Quick lookup by key
SCHEMA_BY_KEY = {entry["key"]: entry for entry in CONFIG_SCHEMA}

# Default placeholder values that indicate a setting hasn't been configured
UNCONFIGURED_VALUES = {
    "your_email@gmail.com",
    "your_app_password_here",
    "CHANGE_THIS_TO_A_RANDOM_SECRET_KEY",
    "NOT_MY_SECRET_KEY",
    "",
}
